title: Bot Documents
description: >
  This repository contains the Privacy Policy and Terms of Service for several discord bots.
theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  input: GFM

# Optional sidebar configuration (if supported by the theme)
sidebar:
  title: "Contents"
  nav:
    - title: "Home"
      url: /
    - title: "Hades' Star ELO Privacy Policy"
      url: /Hades_Star_ELO_Privacy_Policy.md
    - title: "Hades' Star ELO Terms of Service"
      url: /Hades_Star_ELO_Terms_of_Service.md
    - title: "Hades' Star RS Q Privacy Policy"
      url: /Hades_Star_RS_Q_Privacy_Policy.md
    - title: "Hades' Star RS Q Terms of Service"
      url: /Hades_Star_RS_Q_Terms_of_Service.md
